name: tonii-shops
version: '1.0-SNAPSHOT'
main: io.github.toniidev.toniishops.ToniiShops
api-version: '1.21'
permissions:
  shop-creation:
    description: Allows the player to create a shop
  shop-management:
    description: Allows the player to manage his shops
  shop-browsing:
    description: Allows the player to browse other players' shops
  item-selling:
    description: Allows the player to sell his items to the Global Server Shop
  global-shop-access:
    description: Allows the player to buy and sell items from the Global Server Shop
  purse-management:
    description: Allows the player to manage his purse to take money from it
commands:
  give-permission:
    aliases: [givepermission, giveperm, givep, give-perm, give-p]
    usage: /give-permission <user> <permission>
    description: Gives a permission to a player
  remove-permission:
    aliases: [removepermission, removeperm, removep, remove-perm, remove-p]
    usage: /remove-permission <user> <permission>
    description: Removes a permission from a player
  create-shop:
    aliases: [createshop, createsh, create-sh]
    usage: /<command>
    description: Gives the player a chest items in which will be sold at a fixed price that he can choose
  manage-shops:
    aliases: [manageshops, managesh, manage-sh]
    usage: /<command>
    description: Shows a GUI that allows the player to manage the shops that he owns
  browse-shops:
    aliases: [browseshops, browsesh, browse-sh]
    usage: /<command>
    description: Shows a GUI that allows the player to browse all the other shops
  sell-item:
    aliases: [sellitem, sellone, sell-one]
    usage: /<command>
    description: Sells one item of the currently held item stack to the server shop
  sell-all:
    aliases: [sellhand, sellall, sellh, sell-hand, sell-all, sell-h]
    usage: /<command>
    description: Sells the entire currently held item stack to the server shop
  open-shop:
    aliases: [openshop, shop, sh, market]
    usage: /<command>
    description: Access to the server shop
  open-purse:
    aliases: [purse, view-purse, openpurse, viewpurse, purse]
    usage: /<command>
    description: Shows the player a GUI containing all his money
  sell-custom-amount:
    aliases: [sellc, sellamount, sellspecifiedamount, sellcustomamount, sell-specified-amount, sellcustom, sell-custom, sell-c]
    usage: /<command> <amount>
    description: Sells the specified amount of the items that are of the same type of the one that the player is holding in main hand